activeWorkspaceOnFocusChange = true
alternativeDisplays = ''
assignFocusedApp = 'opt+='
assignVisibleApps = 'opt+a'
autoAssignAlreadyAssignedApps = false
autoAssignAppsToWorkspaces = false
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
cornerHiddenApps = []
displayMode = 'static'
enableFocusManagement = false
enableIntegrations = true
enablePictureInPictureSupport = true
enableSpaceControl = true
enableSpaceControlAnimations = true
enableSpaceControlTilesAnimations = true
enableSwipeGestures = true
enableWorkspaceSwitcher = true
enableWorkspaceTransitions = false
focusFrontmostWindow = false
hideAllApps = 'cmd+ctrl+opt+shift+h'
hideUnassignedApps = 'opt+h'
keepUnassignedAppsOnSwitch = false
loopWorkspaces = true
loopWorkspacesOnAllDisplays = false
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = true
restoreHiddenAppsOnSwitch = true
runScriptAfterWorkspaceChange = '/opt/homebrew/bin/sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" WORKSPACE_NUMBER="$WORKSPACE_NUMBER" DISPLAY="$DISPLAY" PROFILE="$PROFILE"'
runScriptOnLaunch = '/opt/homebrew/bin/sketchybar --reload'
runScriptOnProfileChange = '/opt/homebrew/bin/sketchybar --reload'
runScriptOnWorkspaceChange = ''
showFloatingNotifications = true
showMenuBarIcon = false
showMenuBarTitle = false
showRecentWorkspaceWhenActivatedTwice = false
showSpaceControl = 'cmd+ctrl+opt+shift+tab'
showUnassignedApps = 'opt+s'
showWorkspaceSwitcher = 'opt+tab'
skipEmptyWorkspacesOnSwitch = true
spaceControlCurrentDisplayWorkspaces = true
spaceControlHideEmptyWorkspaces = true
spaceControlNumberOfColumns = 0
spaceControlUpdateScreenshotsOnOpen = true
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'nextWorkspace'
swipeLeft4FingerAction = 'nextWorkspace'
swipeRight3FingerAction = 'previousWorkspace'
swipeRight4FingerAction = 'previousWorkspace'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToNextWorkspace = 'cmd+ctrl+opt+shift+right'
switchToPreviousWorkspace = 'cmd+ctrl+opt+shift+left'
switchWorkspaceOnCursorScreen = false
switchWorkspaceWhenPipCloses = true
toggleFlashSpace = 'cmd+ctrl+opt+shift+f'
toggleTheFocusedAppFloating = 'opt+f'
unassignFocusedApp = 'opt+-'
workspaceSwitcherCurrentDisplayWorkspaces = true
workspaceSwitcherShowScreenshots = true
workspaceSwitcherSortByLastActivation = false
workspaceSwitcherVisibleWorkspaces = 5
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999